4429 Report users who have not completed registration
THIS-Institute/thiscovery-monitoring pull request #10
Opened 2022-02-23 16:28 UTC by sophiemachin

2022-02-24 15:29 UTC, this-andy requested changes

2022-02-24 15:29 UTC, this-andy commented on src/auth0_metrics.py
> +        users_not_completed = [u["id"] for u in users_ss if u["id"] not in users_sv_ids]
This info - id and emails - should be added to sns topic

2022-02-24 15:29 UTC, this-andy commented on src/auth0_metrics.py
> +    if event and "day" in event:
Can we make this a separate lambda call

2022-02-25 18:07 UTC, sophiemachin commented on src/auth0_metrics.py
> +        users_not_completed = [u["id"] for u in users_ss if u["id"] not in users_sv_ids]
Fixed

2022-02-25 18:07 UTC, sophiemachin commented on src/auth0_metrics.py
> +    if event and "day" in event:
Fixed

2022-02-28 14:24 UTC, this-andy approved these changes

2022-02-28 15:15 UTC, afs25 commented on src/auth0_metrics.py
> +            u["id"] + " " + u["user_name"]
I think it would be useful to include their email address in the SNS message so that we can easily contact them and/or verify them in Auth0 if needed.

2022-02-28 15:16 UTC, sophiemachin commented on src/auth0_metrics.py
> +            u["id"] + " " + u["user_name"]
Ah this is a misnomer, user_name is the email address. I can forward you an example email if you like?

2022-03-01 21:43 UTC, afs25 commented on src/auth0_metrics.py
> +            u["id"] + " " + u["user_name"]
Got it! No need for an example.

2022-03-03 14:40 UTC, merged